#!/bin/bash
declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;32m" [3]="\033[1;36m" [4]="\033[1;31m" [5]="\033[1;33m" )
barra="\033[0m\e[34m======================================================\033[1;37m"

fun_bar () {
comando="$1"
 _=$(
$comando > /dev/null 2>&1
) & > /dev/null
pid=$!
while [[ -d /proc/$pid ]]; do
echo -ne " \033[1;33m["
   for((i=0; i<10; i++)); do
   echo -ne "\033[1;31m##"
   sleep 0.2
   done
echo -ne "\033[1;33m]"
sleep 1s
echo
tput cuu1 && tput dl1
done
echo -e " \033[1;33m[\033[1;31m####################\033[1;33m] - \033[1;32m100%\033[0m"
sleep 1s
}
#######################################################
clear
echo -e "\E[41;1;38m SISTEMA GERADOR DE KEY PAINEL-SSH \E[0m" # aki vc pode trocar os texto e cores
echo ""
  echo -ne "  \033[1;32m    DESEJA CONTINUAR \033[1;31m? \033[1;33m[S/N]:\033[1;37m "; read res
  if [[ "$res" = n || "$res" = N ]];then
  echo ""
  echo -e "\033[1;31m OK \033[1;32m FINALIZANDO INSTALACAO!\033[0m"
  rm -rf installgerador.sh > /dev/null 2>&1
  rm -rf installgerador-original.sh > /dev/null 2>&1
  sleep 2
  clear
  clear; exit 1
fi

#######################################################
rm /root/pkeyv28 > /dev/null 2>&1
rm $HOME/pkeyv28 > /dev/null 2>&1
rm /bin/keyv28 > /dev/null 2>&1
rm /var/www/html/instalv28 > /dev/null 2>&1
rm /home/instv28 > /dev/null 2>&1
rm /home/BD-Painel-v23.sql > /dev/null 2>&1
rm /home/PAINEL-V.28.zip > /dev/null 2>&1
#######################################################
rm /root/pkeyssh > /dev/null 2>&1
rm $HOME/pkeyssh > /dev/null 2>&1
rm /bin/keyssh > /dev/null 2>&1
rm /var/www/html/installl > /dev/null 2>&1
rm /home/instt > /dev/null 2>&1
rm /home/Plus > /dev/null 2>&1
#######################################################
echo ""
clear
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m          INICIANDO INSTALACAO"
echo -e "\033[1;34m ======================================"
sleep 2
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   5%"
echo -e "\033[1;33mâ— \033[1;32mATUALIZANDO LINUX PODE DEMORAR \033[1;33mâ—\033[0m"
fun_update () {
    apt-get update > /dev/null 2>&1
}
fun_bar 'fun_update'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   23%"
echo -e "\033[1;33mâ— \033[1;32mINSTALANDO O APACHE2         \033[1;33mâ—\033[0m"
fun_apache2 () {
    apt-get install apache2 -y > /dev/null 2>&1
}
fun_bar 'fun_apache2'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   40%"
echo -e "\033[1;33mâ— \033[1;32mINSTALANDO SISTEMAS KEY      \033[1;33mâ—\033[0m"
cd /var/www/html/
fun_instalv28 () {
wget http://vipvps.tk/key-intall-carlos/installl > /dev/null 2>&1
chmod +x /var/www/html/installl
wget http://painelweb.tk/key-intall-carlos/v28/instalv28 > /dev/null 2>&1
chmod +x /var/www/html/instalv28
wget https://raw.githubusercontent.com/SPEEDNET244/SPEEDNET244/main/instalv20 > /dev/null 2>&1
chmod +x /var/www/html/instalv20
}
fun_bar 'fun_instalv28'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
cd
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   68%"
echo -e "\033[1;33mâ— \033[1;32mINSTALANDO SISTEMAS KEY      \033[1;33mâ—\033[0m"
cd /bin/
fun_keyv28 () {
wget http://vipvps.tk/key-intall-carlos/keyssh > /dev/null 2>&1
chmod +x /bin/keyssh
wget http://painelweb.tk/key-intall-carlos/v28/keyv28 > /dev/null 2>&1
chmod +x /bin/keyv28
wget https://raw.githubusercontent.com/SPEEDNET244/SPEEDNET244/main/keyv20 > /dev/null 2>&1
chmod +x /bin/keyv20
}
fun_bar 'fun_keyv28'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
cd
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   88%"
echo -e "\033[1;33mâ— \033[1;32mINSTALANDO SISTEMAS KEY      \033[1;33mâ—\033[0m"
cd /home/
fun_keyv28bd () {
wget http://vipvps.tk/key-intall-carlos/instt > /dev/null 2>&1
chmod +x /home/instt
wget https://raw.githubusercontent.com/SPEEDNET244/SPEEDNET244/main/Plus > /dev/null 2>&1
chmod +x /home/Plus
sed -i -e 's/\r$//' Plus

wget http://painelweb.tk/key-intall-carlos/v28/instv28 > /dev/null 2>&1
chmod +x /home/instv28
wget http://painelweb.tk/key-intall-carlos/v28/BD-Painel-v23.sql > /dev/null 2>&1
wget http://painelweb.tk/key-intall-carlos/v28/PAINEL-V.28.zip > /dev/null 2>&1
wget https://raw.githubusercontent.com/SPEEDNET244/SPEEDNET244/main/instv20 > /dev/null 2>&1
chmod +x /home/instv20
}
fun_bar 'fun_keyv28bd'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
cd
cat /dev/null > ~/.bash_history && history -c
clear
#######################################################
echo ""
echo -e "\033[1;34m ======================================"
echo -e "\033[1;36m           INSTALACAO   95%"
echo -e "\033[1;33mâ— \033[1;32mMONTANDO O SEU LINK-IP      \033[1;33mâ—\033[0m"
IP=$(wget -qO- ipv4.icanhazip.com)
fun_keyv28ip () {
if [[ -e "/var/www/html/installl" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /var/www/html/installl > /dev/null 2>&1
fi
if [[ -e "/var/www/html/instalv28" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /var/www/html/instalv28 > /dev/null 2>&1
fi
if [[ -e "/var/www/html/instalv20" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /var/www/html/instalv20 > /dev/null 2>&1
}
fun_bar 'fun_keyv28ip'
echo -e "\033[1;34m ======================================"
sleep 1s
echo ""
cd
clear
#######################################################
rm /root/installgerador.sh > /dev/null 2>&1
rm /bin/gerar > /dev/null 2>&1
cd /bin/
wget http://painelweb.tk/key-intall-carlos/gerar > /dev/null 2>&1
chmod +x /bin/gerar
sed -i -e 's/\r$//' gerar
cd
rm /root/installgerador-original.sh > /dev/null 2>&1
rm /root/installgerador.sh > /dev/null 2>&1
echo 'gerar' >> /root/.bashrc
cat /dev/null > ~/.bash_history && history -c
#######################################################
echo ""
echo -e "$barra"
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"

echo -e "$barra"
echo -e "\033[1;32m ${cor[5]} 5 ${cor[2]} SEGUNDOS ABRIRA O PAINEL KEY!"
echo -e "$barra"
sleep 1s
clear
#
echo ""
echo -e "$barra"
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"

echo -e "$barra"
echo -e "\033[1;32m ${cor[5]} 4 ${cor[2]} SEGUNDOS ABRIRA O PAINEL KEY!"
echo -e "$barra"
sleep 1s
clear
#
echo ""
echo -e "$barra"
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"

echo -e "$barra"
echo -e "\033[1;32m ${cor[5]} 3 ${cor[2]} SEGUNDOS ABRIRA O PAINEL KEY!"
echo -e "$barra"
sleep 1s
clear
#
echo ""
echo -e "$barra"
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"

echo -e "$barra"
echo -e "\033[1;32m ${cor[5]} 2 ${cor[2]} SEGUNDOS ABRIRA O PAINEL KEY!"
echo -e "$barra"
sleep 1s
clear
#
echo ""
echo -e "$barra"
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"

echo -e "$barra"
echo -e "\033[1;32m ${cor[5]} 1 ${cor[2]} SEGUNDOS ABRIRA O PAINEL KEY!"
echo -e "$barra"
sleep 1s
clear
#
gerar

cat /dev/null > ~/.bash_history && history -c
rm /root/installgerador.sh > /dev/null 2>&1
rm /root/pkeyv28 > /dev/null 2>&1
rm $HOME/pkeyv28 > /dev/null 2>&1
rm /root/pkeyssh > /dev/null 2>&1
rm $HOME/pkeyssh > /dev/null 2>&1
#######################################################
