#!/bin/bash
clear
rm /root/instv20 > /dev/null 2>&1
rm $HOME/instv20 > /dev/null 2>&1
rm /root/instalv20 > /dev/null 2>&1
rm $HOME/instalv20 > /dev/null 2>&1
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "           \033[1;33m \033[1;32mATUALIZANDO LINUX, Pode Demorar \033[1;33m\033[0m"
fun_update () {
    apt-get update -y > /dev/null 2>&1
	apt-get install figlet -y > /dev/null 2>&1
}
fun_bar 'fun_update'
echo ""
clear
IP=$(wget -qO- ipv4.icanhazip.com)
link="SEU-IP-AKI"
echo -e "\E[44;1;37m    INSTALAR O PAINEL SSH/DROP/SSL V.2022     \E[0m"
echo ""
echo -e "                              \033[1;31mBy @speednet \033[1;36m"
echo -e "   SPEEDNET" | figlet 
echo -e "                             \033[1;31mPAINEL WEB 2022\033[1;36m"
echo ""
echo -ne "\033[1;32m INSIRA SUA KEY\033[1;37m: "; read _key_
if [[ -z $_key_ ]]; then
echo ""
echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
sleep 1
clear; exit
fi
wget http://$link/$_key_/instv20 > /dev/null 2>&1
sleep 1
if [[ -f $HOME/instv20 ]]; then
echo -e "\n\033[1;32m KEY VALIDA ! \033[1;32m"
echo ""
sleep 1
echo -ne "\033[1;32m PARA CONTINUAR CONFIRME SEU IP: \033[1;37m"; read -e -i $IP ipdovps
if [[ -z "$ipdovps" ]];then
echo ""
echo -e "\033[1;31m IP INVALIDO\033[1;32m"
sleep 1
clear; exit
fi
source $HOME/instv20
else
echo -e "\n\033[1;31m KEY INVALIDA !\033[0m"
rm /root/instalv20 > /dev/null 2>&1
sleep 1
clear; exit
fi
clear
rm $HOME/instv20 > /dev/null 2>&1
rm /root/instv20 > /dev/null 2>&1
rm /root/instalv20 > /dev/null 2>&1
rm $HOME/instalv20.1 > /dev/null 2>&1
